service: api-reportes

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  role: ${file(../roleARN.yaml):roles.LabRole}
  environment:
    TABLE_NAME: ${self:service}-${opt:stage, 'dev'}
    SECRET_KEY: your_jwt_secret
    AUTH_TOKENS_TABLE: userService-auth-tokens-dev

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /reports/sales
          method: any
          cors: true
      - http:
          path: /reports/sales/{report_id}
          method: any
          cors: true

resources:
  Resources:
    ReportesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: report_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: report_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: ReportTypeIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        LocalSecondaryIndexes:
          - IndexName: ReportDateIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
